"""create dynamic fields in campaign model

Revision ID: 7f0c903f9a3f
Revises: 9ba1e0632f30
Create Date: 2023-06-23 16:52:48.158528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f0c903f9a3f'
down_revision = '9ba1e0632f30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
