"""create campaign model

Revision ID: 9ba1e0632f30
Revises: 
Create Date: 2023-06-23 16:42:23.655406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9ba1e0632f30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('campaign_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('param_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('param_value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tokens_pkey')
    )
    # ### end Alembic commands ###
