"""create dynamic fields in campaign model

Revision ID: b4a6b410560c
Revises: 7f0c903f9a3f
Create Date: 2023-06-23 16:54:11.410535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a6b410560c'
down_revision = '7f0c903f9a3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('xyz', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'xyz')
    # ### end Alembic commands ###
